

DELETE FROM PHIEUDATCHO

CREATE FUNCTION AUTO_IDPDC()
RETURNS VARCHAR(16)
AS
BEGIN
	DECLARE @id VARCHAR(16)
	IF (SELECT COUNT(MaPhieuDatCho) FROM PHIEUDATCHO) = 0
		SET @id = 0
	ELSE
		SELECT @id = MAX(RIGHT(MaPhieuDatCho, 5)) FROM PHIEUDATCHO
		SELECT @id = CASE
			WHEN @id = 99999 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC00001'
			WHEN @id >= 0 and @id < 9 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC0000' + CONVERT(CHAR, CONVERT(INT, @id) + 1)
			WHEN @id >= 9 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC000' + CONVERT(CHAR, CONVERT(INT, @id) + 1)
			WHEN @id >= 99 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC00' + CONVERT(CHAR, CONVERT(INT, @id) + 1)
			WHEN @id >= 999 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC0' + CONVERT(CHAR, CONVERT(INT, @id) + 1)
			WHEN @id >= 9999 THEN CONVERT(VARCHAR,GETDATE(),112) + 'PDC' + CONVERT(CHAR, CONVERT(INT, @id) + 1)
		END
	RETURN @id
END

ALTER TABLE PHIEUDATCHO ADD CONSTRAINT IDPDC DEFAULT(dbo.AUTO_IDPDC()) FOR MaPhieuDatCho

